M48
; DRILL file {KiCad 8.0.3} date 2024-06-20T22:58:00-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-20T22:58:00-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X5.6Y-3.81
X5.7Y-3.81
T2
X5.9526Y-3.7499
X5.9526Y-4.0499
X6.0526Y-3.7499
X6.0526Y-4.0499
T3
X5.5Y-3.53
X5.6Y-3.53
X5.7Y-3.53
M30
